# Generated by Django 6.0.4 on 2026-04-20 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado por vendedor'), ('rechazado', 'Rechazado'), ('preparado', 'Preparado por bodega'), ('enviado', 'Enviado'), ('pagado', 'Pago confirmado'), ('entregado', 'Entregado')], default='pendiente', max_length=30)),
                ('metodo_pago', models.CharField(choices=[('debito', 'Débito'), ('credito', 'Crédito'), ('transferencia', 'Transferencia')], max_length=20)),
                ('tipo_entrega', models.CharField(choices=[('retiro', 'Retiro en tienda'), ('despacho', 'Despacho a domicilio')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
